title: Mohit Kumar
baseURL: 'https://mohitkr.com'
languageCode: en-us
theme: 'hugo-theme-cleanwhite'
disqusShortname: "disqus_Nsi1H5N8J6"
googleAnalytics: "G-N2QSYLPBHF" #UA-262536683-1 #287685958
preserveTaxonomyNames: true
paginate: 10
hasCJKLanguage: true

menu:
  main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 10
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 20
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 30


params:
  bookmarks: true
  about_me: true
  header_image: "images/gohugo-default-sample-hero-image.jpg"
  SEOTitle: "Mohit Kumar | Telecom, Cloud and DevOps Tutor"
  description: "Looking for an expert tutor in Telecom, Cloud and DevOps? Look no further than Mohit Kumar. With years of industry experience and a passion for teaching, Mohit can help you master the latest technologies and advance your career in these rapidly evolving fields"
  keyword: "Telecom, Cloud, DevOps, Tutor, Instructor, Teacher, Expert, Industry experience, Career advancement, Technology mastery, Online courses, Learning resources, Professional development, Telecom networks, Cloud computing, Cloud services, Cloud architecture, DevOps methodologies, Automation, Continuous integration, Continuous delivery, Containerization, Virtualization, Infrastructure as code"
  slogan: "My Life, views and Technology"
  image_404: "images/gohugo-default-sample-hero-image.jpg"
  title_404: "404!! This is not found, Please contact me"
  omit_categories: false
  social:
    rss: true
    linkedin: "https://www.linkedin.com/in/mohitkr05"
    github: "https://github.com/mohitkr05"
    twitter: "https://twitter.com/mohitkrau"
    instagram: "full profile url in instagram"
    medium: "full profile url in medium"
    slack: "full workspace url in slack"
    addtional_menus:
    - title: "ARCHIVE"
      href: "/archive/"
    - title: "NOTES"
      href: "/notes/"
    - title: "ABOUT"
      href: "/about/"
enableRobotsTXT: true
sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml

# Permalinks
permalink: /:categories/:year/:month/:day/:title/


friends: true
bookmarks: false
about_me: true

# Include any custom CSS and/or JS files, url or relative to /static folder
#custom_css: ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
#custom_js: ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

# Sidebar settings
sidebar_about_description:  "Software Developer, Open Source Enthusiast and Life Adventurer"
sidebar_avatar: "images/profile_huae77dc523728ac00e5cf6b5ee6a0296c_1790061_300x0_resize_q75_box.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`


markup:
  tableOfContents:
    endLevel: 2
    startLevel: 1
  highlight:
    style: "dracula"
