title: Mohit Kumar
baseURL: 'https://mohitkr.com'
languageCode: en-us
theme: 'ananke'
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: true
sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml
params:
  text_color: 'black'
  # commentoEnable: true
  body_classes: "avenir bg-near-white"
  author: 'Mohit Kumar'
  favicon: 'images/favicon.ico'
  site_logo: 'images/logo.png'
  description: My life, my views.
  background_color_class: bg-purple
  recent_posts_number: 6
  ananke_socials:
    - name: twitter
      url: 'https://twitter.com/mohitkrau'
    - name: instagram
      url : ""
    - name: youtube
      url : ""
    - name: github
      url : ""
    - name: linkedin
      url : ""
    - name: medium
      url : ""
    - name: slack
      url : ""
    - name: rss
      url : ""
